config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'pages#home'

  get 'pages/home'

  get 'pages/about'

  get 'pages/logon'

  resources :medical_records
  resources :employees
  resources :hospitals
  resources :health_care_providers
  resources :patients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  #Dbelongs_to  :Hospital


end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:employee_id, :first_name, :last_name, :telephone, :department, :title, :pay, :start_date, :hospital_id)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :employee_id %>
    <%= form.number_field :employee_id, id: :employee_employee_id %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :employee_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :employee_last_name %>
  </div>

  <div class="field">
    <%= form.label :telephone %>
    <%= form.number_field :telephone, id: :employee_telephone %>
  </div>

  <div class="field">
    <%= form.label :department %>
    <%= form.text_field :department, id: :employee_department %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :employee_title %>
  </div>

  <div class="field">
    <%= form.label :payrate %>
    <%= form.text_field :pay, id: :employee_pay %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date, id: :employee_start_date %>
  </div>

  <div class="field">
    <%= form.label :hospital_id %>
    <%= form.number_field :hospital_id, id: :employee_hospital_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Employee</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Telephone</th>
      <th>Department</th>
      <th>Title</th>
      <th>Payrate</th>
      <th>Start date</th>
      <th>Hospital</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.employee_id %></td>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.telephone %></td>
        <td><%= employee.department %></td>
        <td><%= employee.title %></td>
        <td><%= employee.pay %></td>
        <td><%= employee.start_date %></td>
        <td><%= employee.hospital_id %></td>
        <td><%= link_to 'Show', employee %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>
<a href="/">Home</a>
<a class="pjax" href="/admin/">admin</a>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee:</strong>
  <%= @employee.employee_id %>
</p>

<p>
  <strong>First name:</strong>
  <%= @employee.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employee.last_name %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @employee.telephone %>
</p>

<p>
  <strong>Department:</strong>
  <%= @employee.department %>
</p>

<p>
  <strong>Title:</strong>
  <%= @employee.title %>
</p>

<p>
  <strong>Payrate:</strong>
  <%= @employee.pay %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @employee.start_date %>
</p>

<p>
  <strong>Hospital:</strong>
  <%= @employee.hospital_id %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>