config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'pages#home'

  get 'pages/home'

  get 'pages/about'

  get 'pages/logon'

  resources :medical_records
  resources :employees
  resources :hospitals
  resources :health_care_providers
  resources :patients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/health_care_provider.rb
class HealthCareProvider < ApplicationRecord
  has_many	:MedicalRecord
end

app/controllers/health_care_providers_controller.rb
class HealthCareProvidersController < ApplicationController
  before_action :set_health_care_provider, only: [:show, :edit, :update, :destroy]

  # GET /health_care_providers
  # GET /health_care_providers.json
  def index
    @health_care_providers = HealthCareProvider.all
  end

  # GET /health_care_providers/1
  # GET /health_care_providers/1.json
  def show
  end

  # GET /health_care_providers/new
  def new
    @health_care_provider = HealthCareProvider.new
  end

  # GET /health_care_providers/1/edit
  def edit
  end

  # POST /health_care_providers
  # POST /health_care_providers.json
  def create
    @health_care_provider = HealthCareProvider.new(health_care_provider_params)

    respond_to do |format|
      if @health_care_provider.save
        format.html { redirect_to @health_care_provider, notice: 'Health care provider was successfully created.' }
        format.json { render :show, status: :created, location: @health_care_provider }
      else
        format.html { render :new }
        format.json { render json: @health_care_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /health_care_providers/1
  # PATCH/PUT /health_care_providers/1.json
  def update
    respond_to do |format|
      if @health_care_provider.update(health_care_provider_params)
        format.html { redirect_to @health_care_provider, notice: 'Health care provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @health_care_provider }
      else
        format.html { render :edit }
        format.json { render json: @health_care_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /health_care_providers/1
  # DELETE /health_care_providers/1.json
  def destroy
    @health_care_provider.destroy
    respond_to do |format|
      format.html { redirect_to health_care_providers_url, notice: 'Health care provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_health_care_provider
      @health_care_provider = HealthCareProvider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def health_care_provider_params
      params.require(:health_care_provider).permit(:hcp_id, :company_name, :address, :city, :state, :telephone)
    end
end

app/helpers/health_care_providers_helper.rb
module HealthCareProvidersHelper
end

app/views/health_care_providers/_form.html.erb
<%= form_with(model: health_care_provider, local: true) do |form| %>
  <% if health_care_provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(health_care_provider.errors.count, "error") %> prohibited this health_care_provider from being saved:</h2>

      <ul>
      <% health_care_provider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :hcp_id %>
    <%= form.number_field :hcp_id, id: :health_care_provider_hcp_id %>
  </div>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name, id: :health_care_provider_company_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :health_care_provider_address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :health_care_provider_city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :health_care_provider_state %>
  </div>

  <div class="field">
    <%= form.label :telephone %>
    <%= form.text_field :telephone, id: :health_care_provider_telephone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/health_care_providers/edit.html.erb
<h1>Editing Health Care Provider</h1>

<%= render 'form', health_care_provider: @health_care_provider %>

<%= link_to 'Show', @health_care_provider %> |
<%= link_to 'Back', health_care_providers_path %>

app/views/health_care_providers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Health Care Providers</h1>

<table>
  <thead>
    <tr>
      <th>Hcp</th>
      <th>Company name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Telephone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @health_care_providers.each do |health_care_provider| %>
      <tr>
        <td><%= health_care_provider.hcp_id %></td>
        <td><%= health_care_provider.company_name %></td>
        <td><%= health_care_provider.address %></td>
        <td><%= health_care_provider.city %></td>
        <td><%= health_care_provider.state %></td>
        <td><%= health_care_provider.telephone %></td>
        <td><%= link_to 'Show', health_care_provider %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>
<a href="/">Home</a>
<a class="pjax" href="/admin/">admin</a>

app/views/health_care_providers/new.html.erb
<h1>New Health Care Provider</h1>

<%= render 'form', health_care_provider: @health_care_provider %>

<%= link_to 'Back', health_care_providers_path %>

app/views/health_care_providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hcp:</strong>
  <%= @health_care_provider.hcp_id %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @health_care_provider.company_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @health_care_provider.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @health_care_provider.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @health_care_provider.state %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @health_care_provider.telephone %>
</p>

<%= link_to 'Edit', edit_health_care_provider_path(@health_care_provider) %> |
<%= link_to 'Back', health_care_providers_path %>