config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'pages#home'

  get 'pages/home'

  get 'pages/about'

  get 'pages/logon'

  resources :medical_records
  resources :employees
  resources :hospitals
  resources :health_care_providers
  resources :patients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/medical_record.rb
class MedicalRecord < ApplicationRecord
  #belongs_to  :Employee,  optional: true
  #belongs_to  :HealthCareProvider,  optional: true

def self.update_records_sql
  <<-SQL
    UPDATE medical_records SET allergies = 'No allergies'
  SQL
end
trigger.after(:create) do
  <<-SQL
    #{ self.update_records_sql }
    WHERE medical_records.allergies = NULL
    SQL
end


end

app/controllers/medical_records_controller.rb
class MedicalRecordsController < ApplicationController
  before_action :set_medical_record, only: [:show, :edit, :update, :destroy]

  # GET /medical_records
  # GET /medical_records.json
  def index
    @medical_records = MedicalRecord.all
  end

  # GET /medical_records/1
  # GET /medical_records/1.json
  def show
  end

  # GET /medical_records/new
  def new
    @medical_record = MedicalRecord.new
  end

  # GET /medical_records/1/edit
  def edit
  end

  # POST /medical_records
  # POST /medical_records.json
  def create
    @medical_record = MedicalRecord.new(medical_record_params)

    respond_to do |format|
      if @medical_record.save
        format.html { redirect_to @medical_record, notice: 'Medical record was successfully created.' }
        format.json { render :show, status: :created, location: @medical_record }
      else
        format.html { render :new }
        format.json { render json: @medical_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medical_records/1
  # PATCH/PUT /medical_records/1.json
  def update
    respond_to do |format|
      if @medical_record.update(medical_record_params)
        format.html { redirect_to @medical_record, notice: 'Medical record was successfully updated.' }
        format.json { render :show, status: :ok, location: @medical_record }
      else
        format.html { render :edit }
        format.json { render json: @medical_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medical_records/1
  # DELETE /medical_records/1.json
  def destroy
    @medical_record.destroy
    respond_to do |format|
      format.html { redirect_to medical_records_url, notice: 'Medical record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medical_record
      @medical_record = MedicalRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medical_record_params
      params.require(:medical_record).permit(:ssn, :first_name, :middle_name, :last_name, :dob, :family_history, :address, :city, :state, :existing_cond, :allergies, :medications, :hcp_id, :telephone, :doctor_first_name, :doctor_last_name, :employee_id, :fasting)
    end
end

app/helpers/medical_records_helper.rb
module MedicalRecordsHelper
end

app/views/medical_records/_form.html.erb
<%= form_with(model: medical_record, local: true) do |form| %>
  <% if medical_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medical_record.errors.count, "error") %> prohibited this medical_record from being saved:</h2>

      <ul>
      <% medical_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ssn %>
    <%= form.number_field :ssn, id: :medical_record_ssn %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :medical_record_first_name %>
  </div>

  <div class="field">
    <%= form.label :middle_name %>
    <%= form.text_field :middle_name, id: :medical_record_middle_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :medical_record_last_name %>
  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.date_select :dob, id: :medical_record_dob %>
  </div>

  <div class="field">
    <%= form.label :family_history %>
    <%= form.text_field :family_history, id: :medical_record_family_history %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :medical_record_address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :medical_record_city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :medical_record_state %>
  </div>

  <div class="field">
    <%= form.label :existing_cond %>
    <%= form.text_field :existing_cond, id: :medical_record_existing_cond %>
  </div>

  <div class="field">
    <%= form.label :allergies %>
    <%= form.text_field :allergies, id: :medical_record_allergies %>
  </div>

  <div class="field">
    <%= form.label :medications %>
    <%= form.text_field :medications, id: :medical_record_medications %>
  </div>

  <div class="field">
    <%= form.label :hcp_id %>
    <%= form.number_field :hcp_id, id: :medical_record_hcp_id %>
  </div>

  <div class="field">
    <%= form.label :telephone %>
    <%= form.number_field :telephone, id: :medical_record_telephone %>
  </div>

  <div class="field">
    <%= form.label :doctor_first_name %>
    <%= form.text_field :doctor_first_name, id: :medical_record_doctor_first_name %>
  </div>

  <div class="field">
    <%= form.label :doctor_last_name %>
    <%= form.text_field :doctor_last_name, id: :medical_record_doctor_last_name %>
  </div>

  <div class="field">
    <%= form.label :employee_id %>
    <%= form.number_field :employee_id, id: :medical_record_employee_id %>
  </div>

  <div class="field">
    <%= form.label :fasting %>
    <%= form.check_box :fasting, id: :medical_record_fasting %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/medical_records/edit.html.erb
<h1>Editing Medical Record</h1>

<%= render 'form', medical_record: @medical_record %>

<%= link_to 'Show', @medical_record %> |
<%= link_to 'Back', medical_records_path %>

app/views/medical_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Medical Records</h1>

<table>
  <thead>
    <tr>
      <th>Ssn</th>
      <th>First name</th>
      <th>Middle name</th>
      <th>Last name</th>
      <th>Dob</th>
      <th>Family history</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Existing cond</th>
      <th>Allergies</th>
      <th>Medications</th>
      <th>Hcp</th>
      <th>Telephone</th>
      <th>Doctor first name</th>
      <th>Doctor last name</th>
      <th>Employee</th>
      <th>Fasting</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medical_records.each do |medical_record| %>
      <tr>
        <td><%= medical_record.ssn %></td>
        <td><%= medical_record.first_name %></td>
        <td><%= medical_record.middle_name %></td>
        <td><%= medical_record.last_name %></td>
        <td><%= medical_record.dob %></td>
        <td><%= medical_record.family_history %></td>
        <td><%= medical_record.address %></td>
        <td><%= medical_record.city %></td>
        <td><%= medical_record.state %></td>
        <td><%= medical_record.existing_cond %></td>
        <td><%= medical_record.allergies %></td>
        <td><%= medical_record.medications %></td>
        <td><%= medical_record.hcp_id %></td>
        <td><%= medical_record.telephone %></td>
        <td><%= medical_record.doctor_first_name %></td>
        <td><%= medical_record.doctor_last_name %></td>
        <td><%= medical_record.employee_id %></td>
        <td><%= medical_record.fasting %></td>
        <td><%= link_to 'Show', medical_record %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>
<a href="/">Home</a>
<a class="pjax" href="/admin/">admin</a>
<%= link_to 'New Medical Record', new_medical_record_path %>

app/views/medical_records/new.html.erb
<h1>New Medical Record</h1>

<%= render 'form', medical_record: @medical_record %>

<%= link_to 'Back', medical_records_path %>

app/views/medical_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ssn:</strong>
  <%= @medical_record.ssn %>
</p>

<p>
  <strong>First name:</strong>
  <%= @medical_record.first_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @medical_record.middle_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @medical_record.last_name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @medical_record.dob %>
</p>

<p>
  <strong>Family history:</strong>
  <%= @medical_record.family_history %>
</p>

<p>
  <strong>Address:</strong>
  <%= @medical_record.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @medical_record.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @medical_record.state %>
</p>

<p>
  <strong>Existing cond:</strong>
  <%= @medical_record.existing_cond %>
</p>

<p>
  <strong>Allergies:</strong>
  <%= @medical_record.allergies %>
</p>

<p>
  <strong>Medications:</strong>
  <%= @medical_record.medications %>
</p>

<p>
  <strong>Hcp:</strong>
  <%= @medical_record.hcp_id %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @medical_record.telephone %>
</p>

<p>
  <strong>Doctor first name:</strong>
  <%= @medical_record.doctor_first_name %>
</p>

<p>
  <strong>Doctor last name:</strong>
  <%= @medical_record.doctor_last_name %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @medical_record.employee_id %>
</p>

<p>
  <strong>Fasting:</strong>
  <%= @medical_record.fasting %>
</p>

<%= link_to 'Edit', edit_medical_record_path(@medical_record) %> |
<%= link_to 'Back', medical_records_path %>