config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'pages#home'

  get 'pages/home'

  get 'pages/about'

  get 'pages/logon'

  resources :medical_records
  resources :employees
  resources :hospitals
  resources :health_care_providers
  resources :patients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/patient.rb
class Patient < ApplicationRecord
  #belongs_to :MedicalRecord
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:fname, :lname, :reason, :room_num, :hospital_id, :entry, :exit, :medications)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fname %>
    <%= form.text_field :fname, id: :patient_fname %>
  </div>

  <div class="field">
    <%= form.label :lname %>
    <%= form.text_field :lname, id: :patient_lname %>
  </div>

  <div class="field">
    <%= form.label :reason %>
    <%= form.text_field :reason, id: :patient_reason %>
  </div>

  <div class="field">
    <%= form.label :room_num %>
    <%= form.number_field :room_num, id: :patient_room_num %>
  </div>

  <div class="field">
    <%= form.label :hospital_id %>
    <%= form.number_field :hospital_id, id: :patient_hospital_id %>
  </div>

  <div class="field">
    <%= form.label :entry %>
    <%= form.datetime_select :entry, id: :patient_entry %>
  </div>

  <div class="field">
    <%= form.label :exit %>
    <%= form.datetime_select :exit, id: :patient_exit %>
  </div>

  <div class="field">
    <%= form.label :medications %>
    <%= form.text_field :medications, id: :patient_medications %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Patients</h1>

<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th>Reason</th>
      <th>Room num</th>
      <th>Hospital</th>
      <th>Entry</th>
      <th>Exit</th>
      <th>Medications</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.fname %></td>
        <td><%= patient.lname %></td>
        <td><%= patient.reason %></td>
        <td><%= patient.room_num %></td>
        <td><%= patient.hospital_id %></td>
        <td><%= patient.entry %></td>
        <td><%= patient.exit %></td>
        <td><%= patient.medications %></td>
        <td><%= link_to 'Show', patient %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>
<a href="/">Home</a>
<a class="pjax" href="/admin/">admin</a>
<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @patient.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @patient.lname %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @patient.reason %>
</p>

<p>
  <strong>Room num:</strong>
  <%= @patient.room_num %>
</p>

<p>
  <strong>Hospital:</strong>
  <%= @patient.hospital_id %>
</p>

<p>
  <strong>Entry:</strong>
  <%= @patient.entry %>
</p>

<p>
  <strong>Exit:</strong>
  <%= @patient.exit %>
</p>

<p>
  <strong>Medications:</strong>
  <%= @patient.medications %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>